# Generated by Django 5.2.7 on 2025-10-16 11:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the chart', max_length=255)),
                ('image', models.ImageField(help_text='Upload PNG or JPEG chart image (max 10MB)', upload_to='charts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ChartAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visual_description', models.TextField(help_text="AI's description of what it sees in the chart")),
                ('pattern_analysis', models.TextField(help_text="Technical patterns identified (e.g., 'lion figure', 'head and shoulders')")),
                ('humorous_prediction', models.TextField(help_text='Fun and humorous market prediction')),
                ('technical_explanation', models.TextField(help_text='Mock-serious technical analysis explanation')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_time_seconds', models.FloatField(blank=True, help_text='Time taken to generate analysis', null=True)),
                ('ai_model_used', models.CharField(default='gpt-4-vision-preview', max_length=100)),
                ('confidence_score', models.FloatField(blank=True, help_text='AI confidence in analysis (0-1)', null=True)),
                ('chart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='django_app.chartupload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
