# Generated by Django 5.2.7 on 2025-10-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartanalysis',
            name='ai_model_used',
            field=models.CharField(default='gpt-4o', max_length=100),
        ),
    ]
